title: Junchi Lv's Homepage
page-top-title: Junchi Lv
top-section-bg-text: Computer Science and Technology
home-subtitle: Junchi Lv&ensp;|&ensp;吕骏驰
copyright-text: '&copy; Junchi Lv 2023-2024. All Rights Reserved.'
