title: Shuaiyin Ma's Homepage
page-top-title: Shuaiyin Ma
top-section-bg-text: Computer Science and Technology
home-subtitle: Shuaiyin Ma&ensp;|&ensp;马帅印
copyright-text: '&copy; Shuaiyin Ma 2024-2025. All Rights Reserved.'
